### ISSUE TITLE
Viewer should be able to open ODF files (.odt, .ods, .odp)

### ISSUE THREAD

**Issue by AlfredHellstern** [mikeebowen/ooxml-viewer-vscode#2]
ODF files are just ZIP files containing a tree of mostly XML files, so are very similar to OOXML files (.docx etc).

**Comment by mikeebowen** [comment]
This feature was added with [version 0.2.0](https://github.com/mikeebowen/ooxml-viewer-vscode/commit/17a0898b61c1059ceca7ab08bbb7e4db5c3d465b)
