### ISSUE TITLE
Viewer should be able to let user view files without an extension (such as "mimetypes" in an .ODT file)

### ISSUE THREAD

**Issue by AlfredHellstern** [mikeebowen/ooxml-viewer-vscode#3]
would be great if a context menu item offered an option like "Open in Notepad". (VS Code already allows user to view a particular file though "Reveal in File Explorer".)

**Comment by mikeebowen** [comment]
@AlfredHellstern , currently it opens a mimetype file in a VS Code tab and displays the contents. Why would we want to open it in a different text editor?

**Comment by AlfredHellstern** [comment]
Don't remember exactly the context, but didn't mean to open in Notepad. Was probably asking for a context menu item in Windows File Explorer under Open With. Which is there now after installing the Viewer (Open With > Visual Studio Code) for a docx file, and indirectly for a "mimetype" file (where a popup gives choices, one of which is Visual Studio Code.
