### ISSUE TITLE
Need indicator as to which package in the folder is being viewed

### ISSUE THREAD

**Issue by tomjebo** [mikeebowen/ooxml-viewer-vscode#4]
![image](https://user-images.githubusercontent.com/4644198/99562393-e1729b00-297c-11eb-92f2-d65ed76325b7.png)

There's no way to know which of the OpenXML packages are currently being shown in the "OOXML VIEWER" tree. For example, in the image above, ABC.docx, ABC1.docx, etc...

**Comment by mikeebowen** [comment]
The name of the open package was added to the title by version [v1.2.0](https://github.com/yuenm18/ooxml-viewer-vscode/releases/tag/v1.2.0)
