### ISSUE TITLE
"document.xml is too large to format" after successful open w/o message

### ISSUE THREAD

**Issue by tomjebo** [mikeebowen/ooxml-viewer-vscode#6]
When opening  a .docx package and viewing document.xml, the part opens in the edit pane just fine, no messages. 
After viewing another part and then reopening the document.xml part, it shows the "too large to format" message.

![image](https://user-images.githubusercontent.com/4644198/101950249-cb39b280-3ba9-11eb-8442-64576195bb71.png)

Looks like this is due to whitespace added when formatting for viewing the first time it's opened. The document.xml part in question is just under the 500K byte limit for formatting (current limit). When formatting the first time, enough space is added to push it over the limit.

**Comment by mikeebowen** [comment]
Thanks for submitting, this is fixed in the 0.9.2 release
